# --- Network Interface Settings ---
# The network interface the DHCP server should listen on (Example: eth0, enp0s3, wlan0)
interface=enp5s0

# --- IP Address Settings ---
# The Static IP Addesss Of This DHCP Server.
server_ip=192.168.1.1
# Network Submask For Client
netmask=255.255.255.0
# Default Gateway (Usually is Server IP)
router=192.168.1.1

# --- IP Pool Settings ---
# Start For Allocated IP (Example: Yu can start IP allcation from .200 )
ip_start=192.168.1.200
# End Of Allocated IP (Accourding To POOL_SIZE Determines The Range Of IP Allcation )
ip_end=192.168.1.250

# --- Release Settings ---
# Release Time (Unit：second)，3600 stands for an hour.
lease_time=3600

# --- DNS Setting (Option) ---
# Provide DNS Server For Client(Example: Google DNS)
dns=192.168.1.1 8.8.8.8
